// <auto-generated />
namespace hwinv.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Seed_DataTypes_Vendors_Os_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seed_DataTypes_Vendors_Os_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "202003080640205_Seed_Data-Types_Vendors_Os_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
